### ISSUE TITLE
Can't compile bluepy on Raspberry Pi

### ISSUE THREAD

**Issue by jpummill** [IanHarvey/bluepy#75]
Sorry if this is a simple question but I am having trouble compiling bluepy on Raspberry Pi:

Already installed libraries:
pi@rasp01 ~ $ sudo apt-get install build-essential libglib2.0-dev libdbus-1-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version.
libdbus-1-dev is already the newest version.
libglib2.0-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 40 not upgraded.

Cloned bluepy:
pi@rasp01 - $ git clone https://github.com/IanHarvey/bluepy.git
pi@rasp01 - $ cd bluepy/bluepy

And tried to compile the source (this is where I ran into problems):
pi@rasp01 ~/bluepy/bluepy $ make
gcc -L. -Os -g -Wall -Werror -DHAVE_CONFIG_H -I../bluez-5.33/attrib -I../bluez-5.33 -I../bluez-5.33/lib -I../bluez-5.33/src -I../bluez-5.33/gdbus -I../bluez-5.33/btio `pkg-config glib-2.0 dbus-1 --cflags` -o bluepy-helper bluepy-helper.c ../bluez-5.33/lib/bluetooth.c ../bluez-5.33/lib/hci.c ../bluez-5.33/lib/sdp.c ../bluez-5.33/lib/uuid.c ../bluez-5.33/attrib/att.c ../bluez-5.33/attrib/gatt.c ../bluez-5.33/attrib/gattrib.c ../bluez-5.33/attrib/utils.c ../bluez-5.33/btio/btio.c ../bluez-5.33/src/log.c ../bluez-5.33/src/shared/mgmt.c ../bluez-5.33/src/shared/crypto.c ../bluez-5.33/src/shared/att.c ../bluez-5.33/src/shared/queue.c ../bluez-5.33/src/shared/util.c ../bluez-5.33/src/shared/io-glib.c ../bluez-5.33/src/shared/timeout-glib.c `pkg-config glib-2.0 --libs`
bluepy-helper.c: In function âconnect_cbâ:
bluepy-helper.c:462:2: error: too few arguments to function âg_attrib_newâ
../bluez-5.33/attrib/gattrib.h:45:10: note: declared here
bluepy-helper.c: In function âcmd_pairâ:
bluepy-helper.c:1180:7: error: unused variable âaddrâ [-Werror=unused-variable]
bluepy-helper.c: In function âcmd_unpairâ:
bluepy-helper.c:1230:7: error: unused variable âaddrâ [-Werror=unused-variable]
bluepy-helper.c: In function âmgmt_debugâ:
bluepy-helper.c:1396:14: error: unused variable âprefixâ [-Werror=unused-variable]
cc1: all warnings being treated as errors
Makefile:26: recipe for target 'bluepy-helper' failed
make: *** [bluepy-helper] Error 1

I am using bluez-5.33 instead of 5.29.

Any insight would be much appreciated.

Thank you!!!

**Comment by IanHarvey** [comment]
The 'too few arguments to function *g_attrib_new()*' is caused by a change between versions 5.29 and 5.33 of bluez. You'll have to stick with the 5.29 source, or fix the problem yourself. (You don't need this to be exactly the same version as the bluez package on your system; the *bluepy-helper* program is self-contained).

The other warnings were fixed in commit 4611544 - if you pull the latest version it should work on current (4.8.x) gcc's.

Thanks
Ian

**Comment by jpummill** [comment]
Thank you!!!
