### ISSUE TITLE
unable to make it work on Python 3.7.3

### ISSUE THREAD

**Issue by David-Afik** [IanHarvey/bluepy#494]
I'm trying to understand what to do for  Python 3.7.3
what line on what file I need to change in order not to get this error:

`Traceback (most recent call last):
  File "BLE_Central_LedControl.py", line 14, in <module>
    import bluepy
  File "/home/pi/bluepy/__init__.py", line 3, in <module>
    bluepy.btle
AttributeError: module 'bluepy' has no attribute 'btle'`

using 
`Name: bluepy
Version: 1.3.0
Summary: Python module for interfacing with BLE devices through Bluez
Home-page: https://github.com/IanHarvey/bluepy
Author: Ian Harvey
Author-email: website-contact@fenditton.org
License: UNKNOWN
Location: /usr/local/lib/python3.7/dist-packages/bluepy-1.3.0-py3.7.egg
Requires:
Required-by:
`

Thanks,
