### ISSUE TITLE
Install issue on raspberry pi zero

### ISSUE THREAD

**Issue by LucaCerina** [IanHarvey/bluepy#204]
Hi,
I have noticed that the isntallation of bluepy (both from pip or source compilation) does not link well the modules, because:

'from bluepy import btle'

goes well if done in the main folder of bluepy, while it returns "cannot import name btle" anywhere else.

**Comment by ozeta** [comment]
I have the same problem

**Comment by rdvmikko** [comment]
Copy&paste from one of my source files:
from bluepy.btle import Scanner, DefaultDelegate, Peripheral, BTLEException

**Comment by ozeta** [comment]
sorry, i forgot to say that it doesn't work on python3

**Comment by LucaCerina** [comment]
the solution of @rdvmikko instead raises a ModuleNotFoundError, but works if the script is executed in the bluepy folder

**Comment by rdvmikko** [comment]
Sorry to hear that. I'm stuck with python 2.7, no problems. Have you checked the python paths and env? I think it might not be a bluepy issue, more like python setup issue maybe..?

**Comment by ozeta** [comment]
I don't know. as the matter of fact, using python 2.7 I can succesfully import the module, but I'm working in 3.4 . how do I check the python setup?

**Comment by IanHarvey** [comment]
Python 3 keeps its packages in a different place (typically `/usr/local/lib/python3.4/dist-packages`) so installing `bluepy` with Python 2's `pip` won't work. (This isn't surprising as much Python 2 code won't work in 3).

On the Pi, Python 3 has a `pip3` which can be installed with:

    sudo apt-get install python3-pip

You can then install Bluepy with:

    sudo pip3 install bluepy

Hope that helps,
Ian

**Comment by ozeta** [comment]
I'll let you know tomorrow!

**Comment by LucaCerina** [comment]
I have already tried both using pip3 and source build (which I believe should lead to the same results...), both of them not working.

The solution for me was to upgrade BlueZ on the raspi from 5.23 (default in Raspbian Jessie) to 5.29, and now it works. I am guessing that the wrong version causes some unhandled exception during the installation

**Comment by ozeta** [comment]
in my case 
`
sudo pip3 install bluepy`

worked just fine! (in my system pip3 was already installed)

**Comment by IanHarvey** [comment]
OK, I'll close this issue for now. I don't suppose you still have a log of any error messages from `pip3` ? There have been a few other installation failures reported, and I'm wondering if there is a common reason.

Thanks
Ian

**Comment by enfrte** [comment]
Not sure if this helps anyone, but I had a similar issue, and it was because I had created a test script called bluepy.py in my home folder. Deleting/renaming the file solved the problem. It seems like python scans the home folder first for library things.
